import os

def build_website(client):

    folder = f"sites/{client.replace('.', '_')}"
    os.makedirs(folder, exist_ok=True)

    html_content = f"""
<html>
<head>
<title>{client} Website</title>
</head>
<body>
<h1>Welcome to {client}</h1>
<p>This website was generated by AI Web Agency.</p>
</body>
</html>
"""

    path = f"{folder}/index.html"

    with open(path, "w") as f:
        f.write(html_content)

    print("Website created:", path)

    return folder
